services:
  mariadb:
    container_name: database_processed
    image: mariadb:latest
    restart: always
    env_file:
      - secrets\mariadb.env
    volumes:
      - database_storage:\var\lib\mysql
    networks:
      - database_network
  redis:
    container_name: database_cache
    image: redis:latest
    restart: always
    env_file:
      - secrets\redis.env
    volumes:
      - database_storage:\data
    networks:
      - database_network
  mongodb:
    container_name: database_raw
    image: mongo:latest
    restart: always
    env_file:
      - secrets\mongodb.env
    volumes:
      - database_storage:\data\db
    networks:
      - database_network
  api:
    container_name: application_api
    build:
      context: ../api/src
      dockerfile: Dockerfile
    restart: always
    working_dir: /work
    volumes:
      - ../api/src:/work
      - ../api/src/node_modules:/work/node_modules
    ports:
      - "81:80"
    env_file:
      - secrets\website.env
  # processor:
  #   container_name: application_data
  #   image: node:current-alpine
  #   restart: always
  #   env_file:
  #     - secrets\processor.env
  #   networks:
  #     - database_network
  #   depends_on:
  #     - mongodb
  #     - mariadb
  angular:
    container_name: application_website
    build:
      context: ../website/src
      target: builder
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../website/src:/project
      - /project/node_modules
    ports:
      - "80:4200"
    env_file:
      - secrets\website.env

volumes:
  database_storage:

networks:
  database_network: